test/cypherTest.js

Switched from e.g. `[ACTED_IN]` to `[:ACTED_IN]` in `expectedCypherQuery`
All tests now do pass.

Added colons in test cases (accompanies 0f6e4bf  which fixes #10)

---

package.json
src/utils.js
test/cypherTest.js

1. Before in `utils` the `cypherDirectiveArgs` function's 
```
`return `{this: ${variable},` + args.substring(1);
```
always put a comma even if there were no arguments following. This resulted in a cypher query e.g. like
```
"... apoc.cypher.runFirstColumn("WITH {this} AS this RETURN this", {this: movie**,}**, true) ...
```
So changed to:
```
return args === "{}" ? `{this: ${variable}${args.substring(1)}` : `{this: ${variable},${args.substring(1)}`
```
This is also relevant when using a `cypher schema directive` to query for Neo4j's internal node `id`, like e.g. `@cypher(statement: "WITH {this} AS this RETURN ID(this)")`.
2. Improved whitespaces in the generated queries by `" $1: "` in args `replace` statement. This is why I needed to update some of `expectedCypherQuery` in existing test …

Handle cypher directive without any params

---

src/index.js

As mentioned in this https://github.com/neo4j-graphql/neo4j-graphql-js/issues/16#issuecomment-352628643 the ("direct") check for scalar types
let fieldIsScalar = fieldType.constructor.name === "GraphQLScalarType";
did not work for mandatory fields ("direct" type then is `GraphQLNonNull` and not `GraphQLScalarType`).
Initially used (https://github.com/neo4j-graphql/neo4j-graphql-js/issues/16#issuecomment-352723555)
let fieldIsScalar = fieldType.ofType ? fieldType.ofType.constructor.name === "GraphQLScalarType" : fieldType.constructor.name === "GraphQLScalarType";
which worked but now "discovered" and already existing helper `function innerType (type)` which recurses through `.oftype` down to eventually `.type` (`GraphQLScalarType` in this case). And it is already used here for `let inner = …

Switched check for scalar types from fieldIsScalar to inner.constructor.name

---

src/index.js

Was finding my queries to id were getting cut short:
`MATCH (group:Group {}) RETURN group {d: apoc.cypher.runFirstColumn("WITH {this} AS this RETURN ID(this)", {this: group}, false), .name , .description } AS group SKIP 0`
...only when called with `apollo-client` and not with graphiql. This change seems to fix the problem...

prevent queries being cut short

---

src/index.js
test/cypherTest.js
test/helpers/cypherTestHelpers.js

This is my first pull request ever, so please let me know if I have missed anything. The change allows filtering of collections at any level in the tree. For example:
{
Movie(title: "River Runs Through It, A") {
title
actors(name: "Tom Hanks") {
name
}
similar(first: 3) {
title
}
}
}

Added parsing of filters on properties with the @relation decorator

---

package.json

After release of version 1.22.0 this package cant be installed in node 8 LTS due to the engines property set in package.json. This PR reverts it back and enables node 8 installs. please merge and release this ASAP.

Fix node 8 install issue

---

.npmignore
package-lock.json
src/index.js
src/selections.js
src/utils.js
test/cypherTest.js
test/helpers/cypherTestHelpers.js

Use parameters at all level of read and mutation queries.
Parameters are added with no prefix for top level parameters, and then an index prefix for all nested parameters.
This index is a monotonically increasing integer, which is incremented when a query selection has any additional parameters to add.
Fixes https://github.com/neo4j-graphql/neo4j-graphql-js/issues/72.

Parameterise queries

---

src/utils.js

Example query:
```gql
query items {
items {
...Foo
}
}
fragment Foo on Item {
name
...Bar
}
fragment Bar on Item {
description
}
```
Currently, neo4j-graphql-js returns only part of the desired data:
```json
"items": [
{
"name": "My name",
"description": null
}
]
```
Effectively ignoring the nested fragment. This simple change allows it to check fragments for nested fragments and return that data as well.

Allow nested fragments

---

src/augmentSchema.js
src/index.js

This contains initial support for makeAugmentedSchema, which returns an augmented schema just like augmentSchema, but can accept typeDefs (see: #88) instead of an already built schema, along with all other arguments of makeExecutableSchema from graphql-tools (resolvers, etc.).

Initial support for #88

---

src/selections.js
src/utils.js
test/cypherTest.js

Use underscore instead of dash for query variables

---

src/augment.js
src/index.js
test/augmentSchemaTest.js
test/cypherTest.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js

In line with #70, if no value is provided for the first ID type field of a generated node creation mutation, then the value will be set using `apoc.create.uuid()` in the cypher translation.
Custom scalars are now included in the arguments of the generated create and update node mutations, and in the `data` argument of relation addition mutations (#109).
The schema augmentation and relation mutation tests have been updated to reflect the API changes made in #108.

ID generation, scalar mutation args, tests

---

src/selections.js

When querying an inlinefragment, its properties are not separated by commas resulting in a invalid cypher query.
For example querying the props `name` and `type` of a `CSVResource`, which implements a `Resource` interface: 
```
(resourcePool_resources:CSVResource) | resourcePool_resources {FRAGMENT_TYPE: "CSVResource", .name  .type }]
```
The bug is that we're looking at the `tailSelections` when checking for adding a comma, but the actual selections which need to be done are inside the inlinefragment. This is why I used `fragmentSelections` here.

(fix) comma-separate properties from inlinefragment

---

src/utils.js

The point of this change is to return better error message in case name or direction haven't been specified into the directive.
If nothing was specified the filter was returning an empty array, and gettting the [0] element was getting undefined in variable direction, and an exception was thrown at the line `return direction.value.value;` : TypeError: Cannot read property 'value' of undefined.
The same apply to getRelationDirection and getRelationName method.
before :
after:
background of the change:
During some discovery of the GRANDStack with my own `schema.graphql` 
I specified the direction: "IN" but on the other type I forgot the "OUT". and when starting docker I received the error message (see first image). Which didn't help me at all until i go to see the source code.

fix(misleading-error): allow to return better error messages

---

src/augment.js
src/augmentSchema.js
src/index.js
src/selections.js
src/translate.js
src/utils.js
test/augmentSchemaTest.js
test/cypherTest.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js

* Don't drop non-Query/Mutation resolvers passed into makeAugmentedExecutableSchema #113
* Basic schema with non nullable property gives error when calling mutation #124
The following `FriendOf` relation type is <i>reflexive</i> in the sense that it comes `from` and goes `to` the same type. There is now support in the generated Query and Mutation API for reflexive relation types. 
```graphql
type User implements Person {
...
rated(rating: Int): [Rated]
friends(since: Int): [FriendOf]
}
type FriendOf {
from: User
since: Int
to: User
}
type Rated {
from: User
rating: Int
to: Movie
}
```
Given the above SDL format (what you write), the following SDL is generated as a result of the schema augmentation process (`augmentSchema` or `makeAugmentedSchema`). The `since` argument on the `friends` is …

Reflexive relation types, fixes for #113 and #124

---

src/index.js

It looks like in PR #125, I forgot to keep a default value for the `resolvers` argument of `makeAugmentedSchema`. This PR resolves that issue -- sorry about that folks!

Fix #126, default resolvers object 

---

src/augment.js
src/augmentSchema.js
src/index.js
src/utils.js
test/augmentSchemaTest.js

This PR is an initial attempt to address #100. In the case of using `makeAugmentedSchema`, directive declarations for `cypher`, `relation`, and `mutationMeta` (used during runtime for relation metadata) will be added to your typeDefs during the schema augmentation process. If you provide declarations for these directives, they will be overwritten. 
If you are using `augmentSchema`, you must use the new export, `augmentTypeDefs` in order to add the directive declarations to your typeDefs, as shown below:
```
import { augmentTypeDefs, augmentSchema } from 'neo4j-graphql-js';
const schema = makeExecutableSchema({
typeDefs: augmentTypeDefs(typeDefs),
resolvers,
});
const augmentedSchema = augmentSchema(schema);
```

Initial support for graphql@14

---

src/augment.js
src/augmentSchema.js
src/index.js
src/utils.js

This PR contains initial support for configuring the schema augmentation process, resolving the following issues:
* How to disable generated mutations? #117
* Prevent auto generation of update, create, ... methods #128
A `config` key is added to the `makeAugmentedSchema` argument object:
```js
const augmentedSchema = makeAugmentedSchema({ 
typeDefs,
config: {
query: true, // default
mutation: false
}
}
```
And the same configuration object is added as a second argument to `augmentSchema`:
```js
const augmentedSchema = augmentSchema(schema, {
mutation: false
});
```
By providing a boolean value, you can prevent the generation of the Query or Mutation API generally. For more fine-grained control, you can provide an array of type names to exclude (such as payload types, etc.) from the schema …

Configuring the schema augmentation process

---

src/augment.js
src/utils.js
test/augmentSchemaTest.js
test/cypherTest.js
test/helpers/testSchema.js

Upon upgrading to GraphQL v14, any return of an `_id` field resulted in an error of the format "Int cannot represent non-integer value: { low: 1, high: 0 }”. In order to resolve this, resources from `neo4j-driver` are now used for reading Integers. In all cases, `_id` fields are now converted to type `String`.

Fix for _id fields in graphql@14

---

src/augment.js
src/selections.js
src/translate.js
src/utils.js
test/augmentSchemaTest.js
test/configTest.js
test/cypherTest.js
test/helpers/cypherTestHelpers.js

This PR contains initial support for nested ordering with the use of `apoc.coll.sortMulti`, to handle for providing a list of values for an `orderBy` argument. Enums and temporal types have also been added as valid ordering values.
#47 (Nested ordering) Specify ordering
#162 Ordering by temporal type
#168 Enum types not added to orderBy
#172 'Maximum call stack size exceeded' on large schema
The `_id` field is no longer added to a type when it is excluded from the generated Query API.
The `first`, `offset`, and `orderBy` arguments can be added to relation type fields during the augmentation process. After which, we can address #173 for ordering by temporal fields on relation types.

Nested ordering, temporal / enum ordering, large schemas

---

src/augment.js
src/index.js
src/selections.js
src/translate.js
src/utils.js
test/augmentSchemaTest.js
test/cypherTest.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js

This PR introduces fixes and improvements to `@cypher` directive fields. 
Passing context values to `@cypher` directive statements is now supported via a dedicated `cypherParams` context object in an Apollo server setup (#187).
In the below example, `currentUserId` is provided in the `cypherParams` context object. It can then be accessed as a Cypher parameter in all `@cypher` directives (including custom queries and mutations).
```js
const server = new ApolloServer({
...,
context: ({ req }) => {
return {
driver,
req,
cypherParams: {
currentUserId: req.user.id
}
};
}
});
```
```graphql
const typeDefs = `
type User {
name: String
currentUserId: String @cypher(statement: """
RETURN $cypherParams.currentUserId
""")
}
`;
```
* Scalar payload types on `@cypher` fields (#145)
* Input type …

Passing context to @cypher, scalar payload mutations, fixes

---

src/utils.js
test/augmentSchemaTest.js
test/cypherTest.js
test/helpers/testSchema.js

This PR contains an additional fix for #136 in order to support providing GraphQL query variables for the individual values of an input type argument on a `@cypher` field.

Fix for input type @cypher argument parameters

---

src/selections.js

This addresses a bug where querying for an interface type without fragments blows up.
I think this is pretty valid - whilst you sometimes want to query with fragments and thus choose one of the implementations of that interface to query I also think it's very valid to query for just the fields on the interface and not choose to extend it to one of the implementations. This does however require that your node has the label of the interface (otherwise there is no label to query on). But that seems pretty reasonable.
Right now I think this is especially important as there seem to be a few other issues around inline fragment support.
I also note there are a few lines of code around these two that don't seem to do anything. Also that `const implementationName` is just a copy of …

Allow interface type to be used when no fragments

---

package-lock.json
src/translate.js
test/cypherTest.js

When writing a custom Cypher mutation using the `@cypher` directive, `cypherParams` would not be passed down into field selections with nested `@cypher` directives. It seems that the `cypherParams` parameter was omitted from `buildCypherSelection` (unlike `customQuery`, which does pass it properly).
Added a unit test to avoid regressions.

bugfix: custom mutation cypher params not being passed

---

src/translate.js
src/utils.js
test/cypherTest.js

Fix #239
First stab at improving order by performance  …
At the moment, it's not quite clear to me how to run the tests locally.
I will let the build server run the tests for now and I hope to see some
tests failing that would give me some direction.
@johnymontana @jexp @michaeldgraham I would be very glad if you could
help me out on how to run tests locally and what test cases you would
expect to see.
~This pull request is still work-in-progress.~

Improve order by performance

---

CONTRIBUTING.md
README.md

I like that @johnymontana has closed my pull request here:
https://github.com/neo4j-graphql/neo4j-graphql-js/pull/243
I don't find the standard CONTRIBUTING guidelines very helpful either.
The only thing that I like to re-use is a hint how to join the neo4j
community on Slack. I guess that would be the best option for new
contributors to get some guidance.
So in this commit I tried to document issues and my workarounds that I
discovered already. I hope other people find this useful.
close #248

Write CONTRIBUTING.md that would have helped me

---

src/utils.js

This does not make that augmented schema's automaticly support federated schema's.
But then again I don't think anyone who uses augmented schema's will be using federation.
Example usage: 
``` javascript
__resolveReference: async (foo: { id: string }, context, resolveInfo) => {
resolveInfo.returnType = 'Foo';
const result = await neo4jgraphql({}, { id: foo.id }, context, resolveInfo);
return result;
}
```

Support for federated schema.

---

test/helpers/cypherTestHelpers.js

Was there any reason for the duplicate code? Which I might have overseen (compatibility or sth.)? :thinking: 
Could you also please merge #253 so I don't have to `git rebase origin/master` all PRs?

DRY augmentedSchemaCypherTestRunner

---

.babelrc
package-lock.json
package.json
src/selections.js
src/translate.js
src/utils.js

In this PR I have changed how the fragments are handled a bit.
Instead of relying on the node matching I would match all nodes that are related with the relation you are fetching. And pass the label as a FRAGMENT_TYPE so the default resolver can do the rest.
This will support default interface queries & multiple fragments and will still return the correct type.
However if your graph would contain multiple labels for a node we would have to pass the entire array of labels and check that instead in the default resolver, I didn't do that yet but if core contributors would like to see this "improvement" I can surely add this here.
I'm quite blocked by this PR so it would be great if there is some feedback here that we can solve this issue as fast as possible.
Looking forward to contribute …

Interfaces - Handle multiple fragments.

---

src/translate.js

Fixed merge commit that did not correctly merge two changes - using
multiple labels on nodes and allowing multiple inline fragments.
Issue number: #289

Fix: possible to query interface

---

CONTRIBUTING.md
test/integration/integration.test.js

The `fail` method in `ava` only accepts a String -- if anything else is passed to it, it blows up with a cryptic "The assertion message must be a string" message. This fixes these calls so that if a test actually fails, the error that caused the test to fail is shown rather than the aforementioned message.
This change also adds a reminder to install APOC to the contributing guidelines.

Fix integration tests

---

src/selections.js

A query on an interface that specifies common fields outside the fragment and other fields inside the fragment will fail with an error on the common fields. E.g.
```
query Area {
Area {
name
__typename
includes{
name
...on Partition {
resident
}
}
}
}
```
This results in an "unable to resolve field Partition.name" error, while this works.
```
query Area {
Area {
name
__typename
includes{
...on Partition {
name
resident
}
}
}
}
```
This fix keeps the common-level fields when processing a fragment

Carry non-fragment fields into the result for a fragment

---

README.md
package-lock.json
package.json
src/augment.js
src/index.js

The motivation for this change is that we have a lot of the following
code:
```js
SomeResolver: async (object, args, context, resolveInfo) => {
...
return neo4jgraphql(object, args, context, resolveInfo, false)
}
```
As soon as we want to debug the generated cypher queries, we only see those
of the augmented resolvers, but not if the call to `neo4jgraphql` happens
in our own custom resolver.
With this commit you can do the following:
```sh
DEBUG=neo4j-graphql-js npm run something
```
and see all the generated cypher queries.
Of course, this can be improved: It would be nice to selectively
filter for certain resolvers like this:
```sh
DEBUG=neo4j-graphql-js:CreatePost npm run something
```
and see only the generated cypher queries for the `CreatePost` resolver.
But that's for another day
- …

Use `debug` for debugging

---

src/translate.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

This fixes a bug where if types had a cased name e.g. `MovieWithCase` then it would be incorrectly referred to later in the query resulting in both an unbounded match and incorrect results.
I believe this should resolve these two open issues:
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/309
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/257

Fix bug where Camel/Pascal cased variables were broken in filters

---

src/translate.js

FIx for  incorrect behaviour when filters are defined on types below the root. Variable created from type-name is replaced with the variableName the function receives which more accurately represents the set that the filter should be applied to. See issue #326

Fix for incorrect behavior in filters 

---

example/apollo-server/movies-schema.js
src/augment/fields.js
src/augment/types/spatial.js
src/augment/types/temporal.js
src/augment/types/types.js
src/index.js
src/selections.js
src/translate.js
src/utils.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/integration/integration.test.js
test/unit/augmentSchemaTest.test.js
test/unit/configTest.test.js
test/unit/cypherTest.test.js

This PR contains initial support for Neo4j spatial properties. 
`Point` types are now translated using updated transformations in the schema augmentation process, similar to the current behavior of the Neo4j temporal types (Time, Date, DateTime, etc.). Output type `Point` fields are transformed to `_Neo4jPoint` and input type `Point` fields are transformed to `_Neo4jPointInput`.
To support this, the following type definitions are now generated in the schema augmentation process:
```graphql
type _Neo4jPoint {
x: Int
y: Int
z: Int
longitude: Int
latitude: Int
height: Int
crs: String
srid: Int
}
input _Neo4jPointInput {
x: Int
y: Int
z: Int
longitude: Int
latitude: Int
height: Int
crs: String
srid: Int
}
```
Similar to the temporal configuration for the augmentation process, generated …

Initial spatial support using Point type

---

src/augment/augment.js
src/augment/fields.js
src/augment/types/node/node.js
src/augment/types/node/query.js
src/augment/types/relationship/query.js
src/augment/types/relationship/relationship.js
src/augment/types/types.js
src/index.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/configTest.test.js

This PR addresses issues #337 and #338 and contains some refactoring of how operation types (Query, Mutation, etc.) get handled in the augmentation process.

Fixes for generated schema type and default config

---

src/augment/input-values.js
src/augment/types/relationship/query.js
src/augment/types/spatial.js
src/translate.js
src/utils.js
test/helpers/filterTestHelpers.js
test/helpers/tck/filterTck.md
test/integration/integration.test.js
test/unit/augmentSchemaTest.test.js

This PR contains initial support for `Point` type spatial filtering. Given a `Point` type field named, for example, `location`, the filtering fields `location`, `location_not`, `location_distance`, `location_distance_lt`, `location_distance_lte`, `location_distance_gt`, `location_distance_gte` will now be generated.
To support the distance filters, the schema augmentation process now generates the following input object type definition,
```graphql
input _Neo4jPointDistanceFilter {
point: _Neo4jPointInput!
distance: Float!
}
```
The following tests have been added to `filterTck.md`: 
```
Spatial field equal to given value
Spatial field different from given value
Spatial field distance with given Point value equal to given value
Spatial field distance with given Point value less than given …
```

Spatial filters

---

src/augment/types/relationship/mutation.js
test/unit/augmentSchemaTest.test.js
test/unit/configTest.test.js

This PR seeks to resolve issues #343 and #344.

Fixes for incorrect and non-existing hasScope directives

---

example/apollo-server/movies-schema.js
src/augment/types/node/mutation.js
src/augment/types/relationship/mutation.js
src/translate.js
src/utils.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/integration/integration.test.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

This PR contains initial support for Merge operations for both nodes and relationships.

Merge operation support

---

example/apollo-server/movies-schema.js
src/augment/fields.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js

This PR resolves issue #359, where if an `_id` field is provided on a type, the augmentation process fails due to an incorrect duplication of corresponding values (`_id_asc`, `_id_desc`) added to the ordering enum generated for that type.

Fix for _id field on generated ordering types

---

.circleci/config.yml
example/apollo-server/movies-middleware.js
example/apollo-server/movies-schema.js
package-lock.json
package.json
scripts/start-neo4j.sh
src/index.js
src/translate.js
src/utils.js
test/integration/integration.test.js
test/unit/cypherTest.test.js

This PR adds support and testing for Neo4j v4.0.
NOTE: The Neo4j v4.0 multi-database functionality is not yet directly exposed via neo4j-graphql.js, instead only the default database is used. Exposing multi-database via neo4j-graphql.js will be addressed in an upcoming release.

Initial support for Neo4j v4.0

---

src/augment/fields.js
src/augment/input-values.js
src/augment/types/node/node.js
src/augment/types/node/query.js
src/augment/types/relationship/relationship.js
src/translate.js
src/utils.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

This PR contains a few fixes:
This issue / inconsistency occurs when a merge node operation creates a node. I realized after the initial PR for merge operations that we should implement the same behavior that the node creation mutation has when the node is an object type implementing an interface - the node recieves both the label of its type and the label of the implemented interface.
This issue concerns the ordering enum type, and corresponding `orderBy` field arguments, being generated for a node type even when that type does not contain at least 1 property type field which could be used for ordering (scalar, temporal, etc.). This issue is avoided when a node is represented by an object type definition, as in such cases we guarantee the existence of at least 1 field - the `_id` field. …

Fixes: merging interface type nodes / using interfaces with no scalars

---

src/translate.js

Issue #295 resulted from no label being added to the Cypher path pattern for related nodes being matched when querying an interface type `@relation` field. To make the path pattern more specific and prevent matching inappropriate nodes, the interface type name is now added as a label. 
For example, given the following schema: 
```graphql
interface Tools {
id: ID
}
type Screwdriver implements Tools {
id: ID
size: Int!
}
type Material {
id: ID!
}
type Product {
materials: [Material!]! @relation(name: "USES", direction: OUT)
tools: [Tools!]! @relation(name: "USES", direction: OUT)
}
```
And this query over the `tools` interface type `@relation` field:
```graphql
query {
Product {
tools {
id
}
}
}
```
Current translation:
```graphql
MATCH (`product`:`Product`) RETURN `product` {tools: …
```

Fixes #295: Querying interface @relation fields with non-unique relationship names

---

src/augment/input-values.js
src/augment/types/relationship/mutation.js
test/integration/integration.test.js
test/unit/augmentSchemaTest.test.js

The `compareSchema` function used in `test/augmentSchemaTest.test.js` had an issue that prevented it from checking for the existence of some generated types. The function and the expected schema for the augmentation test has been updated. Upon the discovery of this issue, I also discovered and tried to resolve two issues in the augmentation process, #369 and #370.

Fixing augmentation testing with related issues #369 & #370

---

src/translate.js
test/helpers/tck/filterTck.md

Use the correct Cypher variable name for filters applied below the root in predicate functions
Addresses #353

fix for nested filtering

---

src/selections.js
test/helpers/cypherTestHelpers.js
test/unit/cypherTest.test.js

Hi @johnymontana ,
We've encountered an issue when using Fragments on relational fields i.c.w. interfaces. Consider the following schema:
```graphql
interface LegalPersonInterface {
id: ID!
}
type MusicGroup implements LegalPersonInterface {
id: ID!
name: String!
members: [LegalPersonInterface] @relation(name: "MEMBER_OF", direction: "OUT")
}
type Actor implements LegalPersonInterface {
id: ID!
name: String!
birthDate: _Neo4jDate
birthPlace: String
}
```
With the schema definition from above, the following query resulted in an error:
```graphql
query {
MusicGroup {
members {
...actorFragment
}
}
}
fragment actorFragment on Actor {
name
birthDate
birthPlace
}
```
This error is shown before this PR:
```
"code": "INTERNAL_SERVER_ERROR",
"exception": {
"stacktrace": [
"Error: Cannot return …
```

Fix fragments on interfaced relational fields

---

src/selections.js
test/unit/cypherTest.test.js

This pull request will fix nested fragments on relations combined with properties.
The following query resulted in an error:
```graphql
fragment moreProperties on Camera {
type
}
fragment properties on CameraMan {
cameras {
id
...moreProperties
}
}
query {
CameraMan {
...properties
}
}
```
Caused by #377

Fix nested fragments on relations

---

example/apollo-server/movies-schema.js
src/augment/fields.js
src/selections.js
src/translate.js
src/utils.js
test/helpers/cypherTestHelpers.js
test/helpers/tck/filterTck.md
test/helpers/testSchema.js
test/integration/integration.test.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

This PR attempts general support for using inline fragments and fragment spreads when querying interface or object types. 
The translation strategy for interface types is extended to handle the complexity that arises from possibly using combinations of inline or spread fragments when querying an interface. 
For example, consider this reduced version of the types used in the tests added by this PR:
```graphql
interface Camera {
id: ID!
type: String
}
type OldCamera implements Camera {
id: ID!
type: String
smell: String
}
type NewCamera implements Camera {
id: ID!
type: String
features: [String]
}
```
A query for an interface type might select only fields on that interface. 
```graphql
query {
Camera {
id
type
}
}
```
In contrast, it might select only fields on types implementing the …

Translating fragments on interface types

---

example/apollo-server/movies-schema.js
src/augment/input-values.js
src/augment/resolvers.js
src/augment/types/node/node.js
src/augment/types/node/query.js
src/augment/types/types.js
src/selections.js
src/translate.js
src/utils.js
test/helpers/cypherTestHelpers.js
test/helpers/tck/filterTck.md
test/helpers/testSchema.js
test/integration/integration.test.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

This PR contains initial support for union types.

Initial support for union types

---

src/selections.js

Fixes #412.
Also, fixed a typo on variable name.

Check if the fragment already exists before pushing into selection array.

---

src/auth.js

Allow overriding of `graphql-auth-directives` whilst leveraging the schema augmentation funcitonality afforded by: `config.auth`.
With this feature, one can create a schema like so: 
```
export const schema = makeAugmentedSchema({
resolvers,
typeDefs,
config: {
auth: {
hasScope: true,
},
},
schemaDirectives: {
hasScope: MyHasScopeDirective,
},
});
```
This, among other things, allows the separation of the token decoding/authentication logic from the authorisation logic.

Allow overriding of graphql-auth-directives 

---

package-lock.json
package.json
src/federation.js

Fix issue [#420](https://github.com/neo4j-graphql/neo4j-graphql-js/issues/420)

install apollo-server-errors and import ApolloError from it in federation.js

---

example/apollo-server/bookmarks.js
package.json
src/index.js

Check the context object for a `neo4jBookmarks` value and pass
along during session creation if the value exists.
For example, to set the `context.neo4jBookmarks` value from a request header (in this case `headers.neo4jbookmarks`) using Apollo Server:
```js
const server = new ApolloServer({
schema,
context: ({ req }) => {
return {
driver,
neo4jBookmarks: req.headers['neo4jbookmark']
};
}
});
```

Add initial support for bookmarks

---

src/translate.js
test/helpers/tck/filterTck.md

This PR contains an initial fix for issue #446

Fix for issue #446

---

src/augment/ast.js
src/augment/fields.js
src/augment/input-values.js
src/augment/types/node/node.js
src/augment/types/relationship/query.js
src/augment/types/relationship/relationship.js
src/augment/types/types.js
src/selections.js
src/translate.js
test/helpers/cypherTestHelpers.js
test/helpers/tck/filterTck.md
test/helpers/tck/parser.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

This PR includes various bug fixes that open up API features for interfaced `@relation` type fields, as well as some fixes to long-standing bugs with relationship field `orderBy` arguments.
#142 - Relationship with properties doesn't build with interface types.
The schema augmentation process now handles `@relation` types that use an interface type for either or both of it's incoming and outgoing node types.
* [query interfaced relationship type field for outgoing object type nodes](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/b5f857fa05b53c7b7e5263df6716e3dc9f71b62b/test/unit/cypherTest.test.js#L2623)
* [query interfaced relationship type field for incoming interface type nodes](https://github.com/neo4j-graphql/neo4j-graphql-js/blob/b5f857fa05b53c7b7e5263df6716e3dc9f71b62b/test/ …

Relationship API bug fixes & updates

---

src/translate.js
test/unit/cypherTest.test.js

#218 - Relationship mutation wrong return when only "to" fields are requested
* [Add relationship mutation and query only outgoing nodes](https://github.com/michaeldgraham/neo4j-graphql-js/blob/e3209e3394510a14b39b3da491482e8b1058d1e1/test/unit/cypherTest.test.js#L781)
* [Remove relationship mutation and query only outgoing nodes](https://github.com/michaeldgraham/neo4j-graphql-js/blob/e3209e3394510a14b39b3da491482e8b1058d1e1/test/unit/cypherTest.test.js#L1848)
* [Update relationship mutation with relationship property and query only outgoing nodes](https://github.com/michaeldgraham/neo4j-graphql-js/blob/e3209e3394510a14b39b3da491482e8b1058d1e1/test/unit/cypherTest.test.js#L781)

Fix for #218

---

src/augment/fields.js
src/augment/types/node/mutation.js
src/augment/types/node/node.js
src/augment/types/node/query.js
src/augment/types/relationship/mutation.js
src/augment/types/relationship/relationship.js
src/selections.js
src/translate.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

* **Fragments**<br><br>
* Fixes #429 - Invalid input in generated query when using inline fragments inside fragments<br>
When querying an interface type, a fragment can now be used on that same interface type:
* [query only interface type fields using fragments](https://github.com/michaeldgraham/neo4j-graphql-js/blob/dbab3302dfec5ed2afffb72e51bfd86a95cb77cf/test/unit/cypherTest.test.js#L6905)
* [query fields on interface and implementing object type using only fragments](https://github.com/michaeldgraham/neo4j-graphql-js/blob/dbab3302dfec5ed2afffb72e51bfd86a95cb77cf/test/unit/cypherTest.test.js#L6938)
* [query fields on interface and implementing object types using only fragments](https://github.com/michaeldgraham/neo4j-graphql-js/blob/dbab3302dfec5ed2afffb72e51bfd86a95cb77cf/test/unit/cyp …

Bug fixes for v2.16.0: Fragments, relationship types, and merge mutations

---

src/augment/directives.js
src/augment/fields.js
src/augment/types/node/mutation.js
src/augment/types/node/node.js
src/augment/types/node/selection.js
src/augment/types/relationship/mutation.js
src/augment/types/relationship/relationship.js
src/augment/types/types.js
src/index.js
src/schemaAssert.js
src/selections.js
src/translate.js
src/utils.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/unit/assertSchema.test.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

This PR resolves #484 by introducing optional `@id`, `@unique`, and `@index` field directives for asserting [unique property constraints](https://neo4j.com/docs/cypher-manual/current/administration/constraints/#administration-constraints-unique-nodes) and [property indexes](https://neo4j.com/docs/cypher-manual/current/administration/indexes-for-search-performance/#administration-indexes-create-a-single-property-index) on node type fields, and for supporting declarative identification of a primary key field. Further, once we support generating input object mutation arguments (#497), we could better distinguish which arguments are used as keys. Fields with these directives could then be used for generating mutation API that supports using multiple keys for rich node selection in a …

Declarative primary keys, constraints and indexes with @id, @unique, and @index directives

---

src/augment/augment.js
src/augment/directives.js
src/augment/fields.js
src/augment/input-values.js
src/augment/types/node/node.js
src/augment/types/node/query.js
src/augment/types/relationship/query.js
src/augment/types/relationship/relationship.js
src/augment/types/types.js
src/schemaAssert.js
src/selections.js
src/translate.js
src/utils.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

* List Fields
* #221 - How to generate a query for a [String] type  
List arguments are now generated and translated for Scalar, Enum, Temporal, and Point type list fields. <br>
* #350 - Feature request: Filters for list properties
List filters are now generated and translated for Scalar, Enum, Temporal, and Point type list fields. 
* Computed Fields
* #463 - Cypher statements in cypher directives should escape special characters
The augmentation process now escapes double-quotes used within a multi-line `@cypher` statement.
* Integers
* #464 Integers being converted to floats in Neo4j database
`Int` type field argument values used in the mutation API are now appropriately converted to Neo4j integers using `neo4j-driver`.

Field arguments and filters for list type fields

---

src/index.js

This refactors the query and schema assertion code to follow the best practice of consuming query results inside the Transaction function closures.

Consume results inside Transaction functions

---

src/augment/ast.js
src/augment/fields.js
src/augment/types/node/mutation.js
src/augment/types/node/query.js
src/augment/types/relationship/mutation.js
src/augment/types/relationship/query.js
src/augment/types/relationship/relationship.js
src/augment/types/spatial.js
src/augment/types/temporal.js
src/augment/types/types.js
test/integration/integration.test.js
test/unit/augmentSchemaTest.test.js
test/unit/configTest.test.js

This PR is an initial implementation addressing #483, for generating schema documentation by building AST descriptions during the augmentation process.

Initial documentation descriptions for generated API

---

src/augment/directives.js

Let the user define an environment variable `AUTH_ROLE_ENUM_NAME` if he needs to use the name `Role` for something else.
While `hasScope` and `hasRole` are useful for basic authorization cases, other cases are better handled with a Role type and relationships instead of an enum.
I would like to be able to use `Role` for a graphql type, and `RoleTitle` for the graphql-auth-directives required enum name.
Example:
```graphql
enum RoleTitle {
ADMIN
STAFF
TRAINER
STUDENT
}
type Role {
title: RoleTitle!
scopes: [Scope!]
users: [User!] @relation(name: "HAS", direction: "IN")
}
type User {
role: Role @relation(name: "HAS", direction: "OUT")
}
type Mutation {
updateUserRole(id: ID!, role: RoleTitle): User
@hasScope(scopes: ["User: UpdateRole"])
@cypher(
statement: """
MATCH (u1:User {id: …
```

feat: User-defined Role enum name

---

package-lock.json
src/augment/directives.js
src/augment/input-values.js
src/augment/types/node/node.js
src/augment/types/relationship/mutation.js
src/augment/types/relationship/query.js
src/augment/types/relationship/relationship.js
src/augment/types/types.js
src/selections.js
src/translate.js
src/utils.js
test/helpers/cypherTestHelpers.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js

The current way to define the head and tail node types of a `@relation` type requires the user to define `from` and `to` fields. For example:
```graphql
type Cause {
id: ID! @id
causes: [Event]
}
type Effect {
id: ID! @id
causedBy: [Event]
}
type Event @relation { #default name = "EVENT"
from: Cause
to: Effect
description: String
}
```
```graphql
type Cause {
id: ID! @id
effects: [Effect]
}
type Effect @relation {
from: Cause
to: Cause
description: String
}
```
This PR adds `from` and `to` arguments to the `@relation` type directive used by schema augmentation. The `from` argument is for the name of the node type field the relationship is coming from (head node), and the `to` argument for the node type it's going to (tail node). This results in adding a layer of customization for the …

@relation type directive arguments for custom node type field names

---

src/augment/augment.js
src/index.js

The graphql-tools documentation [suggests to write functional directives instead of class-based ones](https://www.graphql-tools.com/docs/schema-directives/).
This can be done with neo4j-graphql-js by allowing the `schemaTransforms` key to makeAugmentedSchema:
```ts
const schema = makeAugmentedSchema({
typeDefs,
schemaTransforms: [canUpdateRoleTransformer],
});
```
<details><summary>Example of functional directive I could get working with my fork of neo4j-graphql-js</summary>
```ts
const canUpdateRoleTransformer = (schema: GraphQLSchema): GraphQLSchema =>
mapSchema(schema, {
[MapperKind.OBJECT_FIELD]: (fieldConfig) => {
let directives: DirectiveUseMap;
try {
directives = getDirectives(schema, fieldConfig);
} catch {
// GraphQLError [Object]: Argument "direction" has invalid value "BOTH". …
```

feat: allow functional directives via schemaTransforms

---

package.json
src/augment/input-values.js
src/augment/types/node/mutation.js
src/augment/types/node/node.js
src/augment/types/node/selection.js
src/augment/types/relationship/mutation.js
src/selections.js
src/translate.js
src/utils.js
test/helpers/augmentSchemaTestHelpers.js
test/helpers/experimental/augmentSchemaTest.js
test/helpers/experimental/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/cypherTest.test.js
test/unit/experimental/augmentSchemaTest.test.js
test/unit/experimental/cypherTest.test.js

This PR adds initial support for generating input object arguments for node and relationship mutations. A documentation update preview is available at: https://deploy-preview-59--distracted-golick-08ed24.netlify.app/docs/graphql-schema-generation-augmentation#experimental-api. 
To prevent breaking changes moving forward, the new API is available under this configuration flag: 
```js
config: {
experimental: true
}
```
In the below schema, we have a `User` type and a `Movie` type. Each has an `@id` field along with at least one other `@unique` or `@index` field:
```graphql
type User {
idField: ID! @id
name: String
birthday: DateTime
uniqueString: String! @unique
indexedInt: Int @index
rated: [Rating]
}
extend type User {
extensionString: String!
}
type Rating @relation(from: "user", to: …
```

Input object argument format for mutation API

---

src/augment/types/node/mutation.js
src/augment/types/node/selection.js
src/translate.js
test/helpers/experimental/augmentSchemaTest.js
test/helpers/experimental/testSchema.js
test/unit/experimental/augmentSchemaTest.test.js
test/unit/experimental/cypherTest.test.js

This PR fixes some issues in the initial implementation of the experimental node mutation API introduced in #531. Given a `User` node type, the `_UserData` input object generated for the `data` argument of `Create`, `Merge`, and `Update` mutations was failing to preserve list type wrappers and nullability. So, `Create` and `Merge` now use a new `_UserCreate` input object, which preserves nullability and `Update` uses a `_UserUpdate` input object that keeps arguments optional. In both cases, list type wrappers are preserved, appropriately allowing for list arguments. 
Docs update: https://deploy-preview-60--distracted-golick-08ed24.netlify.app/docs/graphql-schema-generation-augmentation#experimental-api

Experimental mutation API: Fixes for data input objects

---

package.json
src/augment/augment.js
src/augment/directives.js
src/translate.js
src/utils.js
test/helpers/custom/customSchemaTest.js
test/helpers/custom/testSchema.js
test/helpers/experimental/augmentSchemaTest.js
test/helpers/experimental/custom/customSchemaTest.js
test/helpers/experimental/custom/testSchema.js
test/helpers/testSchema.js
test/unit/augmentSchemaTest.test.js
test/unit/custom/cypherTest.test.js
test/unit/experimental/augmentSchemaTest.test.js
test/unit/experimental/custom/cypherTest.test.js

This PR adds support for using the `@cypher` directive on INPUT_FIELD_DEFINITION, allowing for custom nested mutations that are translated using Cypher [correlated subqueries](https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/), available in Neo4j version 4.1.
Initial documentation: https://deploy-preview-60--distracted-golick-08ed24.netlify.app/docs/guide-graphql-schema-design#custom-nested-mutations
Schema: https://github.com/michaeldgraham/neo4j-graphql-js/blob/master/test/helpers/custom/testSchema.js
Tests: https://github.com/michaeldgraham/neo4j-graphql-js/blob/master/test/unit/custom/cypherTest.test.js
As of PR #531, when `config.experimental = true`, the arguments for generated node mutations have an input object format. Nested `@cypher` input fields also work for …

Custom nested mutations using @cypher on input fields
